- name: Configure mysql server
  hosts: mysql
  become: yes
  tasks:
    - name: Install MySQL Server 8.0.x
      ansible.builtin.package:
        name: mysql-server
        state: installed

    - name: Start and enable MySQL Service
      ansible.builtin.service:
        name: mysqld
        state: started
        enable: yes