- name: Configure mysql server
  hosts: mysql
  become: yes

  vars:
    mysql_root_password: ExpenseApp@1

  tasks:
    - name: Install MySQL Libraries
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
      - cryptography
      - PyMySQL

    - name: Install MySQL Server 8.0.x
      ansible.builtin.package:
        name: mysql-server
        state: installed

    - name: Start and enable MySQL Service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

# Next, We need to change the default root password in order to start using the database service. Use password ExpenseApp@1 or any other as per your choice.

    - name: connect to mysql Server
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: mysql.meetshabu.online
      register: mysql_info
      ignore_errors: true
    
    - name: Print the output of mysql
      ansible.builtin.debug:
        msg: " mysql info is {{ mysql_info }}"

    - name: Setting the root password
      ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_root_password }} "
      when: mysql_info.failed is true

